version: '3'

services:
  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      #- DATABASE_URL=authenticationDB
    ports:
      - 3306:3306 #mapiramo nas port na port kontejnera

  adminer:
    image: adminer
    ports:
      - 8080:8080
